<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
?>

<meta property="og:type" content="og:category" />
<meta property="og:site_name" content="Beyoung" />
<meta property="og:url" content="<?php echo $category->getUrl();?>" />
<meta property="og:title" content="<?php echo $category->getName();?>" />
<meta property="og:image" content="<?php echo $category->getImageUrl();?>" />
<meta property="og:image:width" content="200" />
<meta property="og:image:height" content="200" />
<meta property="og:image:alt" content="<?php echo $category->getName();?>" />
<meta property="og:description" content="<?php echo $category->getMetaDescription();?>" />
<meta property="fb:app_id" content="1795968774032189" />

<meta name="twitter:app:country" content="IN" />
<meta name="twitter:card" content="" />
<meta name="twitter:site" content="@BeyoungFolks" />
<meta name="twitter:description" content="<?php echo $category->getMetaDescription();?>" />
<meta name="twitter:title" content="<?php echo $category->getName();?>" />
<meta name="twitter:creator" content="@BeyoungFolks" />
<meta name="twitter:image" content="<?php echo $category->getImageUrl();?>"/>
