<?php 
$jsUrl = $this->getX3JsUrl();
$limit = $this->_default_page_size;
$categories = $this->getAllImageCategories();
$productId = $this->getCurrentProductId();
$isProductColorTabEnable = $this->pdcHelper->isProductColorTabEnable($productId);
$productConfigsInfo = $this->getProductConfig();
$productConfigs = array();
if(isset($productConfigsInfo['note'])) {
    $productConfigs = $productConfigsInfo['note'];
}
?>
<input type="hidden" value='<?php echo $limit;?>'  id="default_page_size" />
<input type="hidden" value='<?php echo htmlentities($categories);?>' id="pdc-image-categories" />
<div class="pdc-tabs">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs tabs-left">
        <?php if(isset($productConfigs['enable_product_design_tab']) && $productConfigs['enable_product_design_tab'] == 1): ?>
		<li><a class="a-product-design" href="#productDesign" data-toggle="tab"><i class="fa fa-dashcube"></i> <?php echo __("Product Design") ?></a></li>
		<?php endif; ?>
        <?php if(isset($productConfigs['enable_elements_tab']) && $productConfigs['enable_elements_tab'] == 1): ?>
        <li><a class="a-apps" href="#apps" data-toggle="tab"><i class="fa-skyatlas fa"></i> <?php echo __("Add Clipart") ?></a></li>
		<?php endif; ?>
        <?php if(isset($productConfigs['enable_upload_tab']) && $productConfigs['enable_upload_tab'] == 1): ?>
        <li><a class="a-upload" href="#upload" data-toggle="tab"><i class="fa-cloud-upload fa"></i> <?php echo __("Upload Image") ?></a></li>
		<?php endif; ?>
        <?php if(isset($productConfigs['enable_text_tab']) && $productConfigs['enable_text_tab'] == 1): ?>
        <li><a class="a-text" href="#text" data-toggle="tab"><i class="fa fa-font"></i> <?php echo __("Add Text") ?></a></li>
		<?php endif; ?>
        <?php if(isset($productConfigs['enable_layer_tab']) && $productConfigs['enable_layer_tab'] == 1): ?>
        <li><a class="a-layers" href="#layers" data-toggle="tab"><i class="fa fa-tasks"></i> <?php echo __("Layers") ?></a></li>
		<?php endif; ?>
        <?php if(isset($productConfigs['enable_info_tab']) && $productConfigs['enable_info_tab'] == 1): ?>
        <li><a class="a-info" href="#info" data-toggle="tab"><i class="fa fa-support"></i> <?php echo __("Info") ?></a></li>
        <?php endif; ?>
        <?php if(isset($productConfigs['enable_zoom_btn']) && $productConfigs['enable_zoom_btn'] == 1): ?>
		<li>
			<div class="pdc-zoom hidden-md hidden-lg"><!--Mobile Zoom-->
				<button type="button" class="btn-zoom btn-zoom-in"><span><i class="fa fa-search-plus"></i> <?php echo __('Zoom In');?></span></button>
				<input type="text" disabled="disabled" class="input-zoom" value="100%"/>
				<button type="button" class="btn-zoom btn-zoom-out"><span><i class="fa fa-search-minus"></i> <?php echo __('Zoom Out');?></span></button>
				<button type="button" class="btn-zoom btn-zoom-reset"><span><i class="fa fa-compress"></i> <?php echo __('Reset');?></span></button>
			</div>
		</li>
        <?php endif; ?>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <div class="toggle-cont">
            <a id="toggle-app-button" class="left"><img src="<?php echo $jsUrl . 'images/close.png';?>" alt="<?php echo __("Close");?>" /></a>
        </div>
		<!-- Product Design tab content -->
        <?php if(isset($productConfigs['enable_product_design_tab']) && $productConfigs['enable_product_design_tab'] == 1): ?>
		<div class="tab-pane" id="productDesign">
			<h3><?php echo __('Product Design'); ?></h3>
            <?php echo $this->getLayout()->createBlock('Magebay\Pdc\Block\X3')->setTemplate('Magebay_Pdc::x3/design/left-area/product_design.phtml')->toHtml(); ?>																			
        </div>
        <?php endif; ?>
		<!-- Elements tab content -->
        <?php if(isset($productConfigs['enable_elements_tab']) && $productConfigs['enable_elements_tab'] == 1): ?>
		<div class="tab-pane" id="apps">
			<h3><?php echo __('Elements'); ?></h3>
            <?php echo $this->getLayout()->createBlock('Magebay\Pdc\Block\X3')->setTemplate('Magebay_Pdc::x3/design/left-area/app.phtml')->toHtml(); ?>																				
        </div>
        <?php endif; ?>
		<!-- Upload Tab  tab content -->
        <?php if(isset($productConfigs['enable_upload_tab']) && $productConfigs['enable_upload_tab'] == 1): ?>
        <div class="tab-pane" id="upload">
			<h3><?php echo __('Upload'); ?></h3>
            <?php echo $this->getLayout()->createBlock('Magebay\Pdc\Block\X3')->setTemplate('Magebay_Pdc::x3/design/left-area/product_upload.phtml')->toHtml(); ?>																				
        </div>
        <?php endif; ?>
		<!-- Add Text  tab content -->
        <?php if(isset($productConfigs['enable_text_tab']) && $productConfigs['enable_text_tab'] == 1): ?>
		<div class="tab-pane" id="text">
			<h3><?php echo __('ADD TEXT'); ?></h3>
			<div class="text-content">
				<div class="text-effect">
					<h3><?php echo __("Text Effects") ?></h3>
					<div class="curved-text-wrapper">
						<?php echo $this->getLayout()->createBlock('Magebay\Pdc\Block\X3')->setTemplate('Magebay_Pdc::x3/design/left-area/curvedtext.phtml')->toHtml(); ?>
					</div>
				</div>
			</div>
        </div>
        <?php endif; ?>
		<!-- Layers tab content -->
        <?php if(isset($productConfigs['enable_layer_tab']) && $productConfigs['enable_layer_tab'] == 1): ?>
		<div class="tab-pane" id="layers">
			<h3><?php echo __('LAYERS'); ?></h3>
            <?php echo $this->getLayout()->createBlock('Magebay\Pdc\Block\X3')->setTemplate('Magebay_Pdc::x3/design/layer.phtml')->toHtml(); ?>
        </div>
        <?php endif; ?>
        <!-- Info Tab -->
        <?php if(isset($productConfigs['enable_info_tab']) && $productConfigs['enable_info_tab'] == 1): ?>
        <div class="tab-pane" id="info">
			<h3><?php echo __('HELP INFORMATION'); ?></h3>
            <div class="pdc-show-content">
            
            		<h4 style="color:red">
            		If you are facing any kind of issue, you can directly reach us at: <a href="mailto:help@beyoung.in">help@beyoung.in</a>
            	</h4>
				
            	<p style="font-size: 12px;"> If you need to change product color, then you can switch it from product design section</p>
            	<p style="font-size: 12px;"> You can upload your own image from the upload image section
            		</p>
            		<p style="font-size: 12px;"> You can use clipart images from the Add Clipart section
            		</p>
            		<p style="font-size: 12px;">
            			You can add formatted text from the add text section. Also you can use this section for jersey number and name as well.
            		</p>
            		<p style="font-size: 12px;"> From the layers section you can lock and delete them</p>
					<p style="font-size: 12px;"> If you are using this tool in mobile device, then please use in portrait mode for better use</p>
				            		                
                <?php $productData = $this->getProductInfo(); ?>
                <?php echo isset($productData['short_description']) ? $productData['short_description'] : '';  ?>
            </div>
		</div>
        <?php endif; ?>
    </div>
</div>