<?php
$fonts = $this->pdcHelper->getFonts();
$colors = $this->getColors();
$includeColors = $this->getProductIncludeColors();
$includeFonts = $this->getProductIncludeFonts();
$productConfig = $this->getProductConfig();
?>
<div class="pdc-edit-tool-left"  id="pdc_toolbar_options_left">
	<div class="pdc-edit-top">
		<span class="title"><?php echo __("Text") ?></span>
		
	</div>
    <div id="pdc_text_edit">
        <textarea type="text" pdc-data="text" id="text_edit_form" style="margin-left: 0px; margin-right: 0px; width: 300px;"></textarea>
    </div>
		
    <div class="pdc-item-tool pdc-fonts-family pdc_edit_text_only text-left" >	
		<span class="title"><?php echo __("Font") ?></span>
		<div class="pdc-fonts-content">
			<select class="pdc-style-family" style="font-family:">
				<option style="font-family:Arial;" value="<?php echo __("Arial") ?>"><?php echo __("Arial") ?></option>
				<?php foreach ( $fonts as $font) : ?>
					<?php 
					if(is_array($includeFonts)) {
						if(!in_array($font->getFontId(), $includeFonts)) continue;  
					} 
					?>
					<?php $displayText = $font->getDispayText() ? $font->getDispayText() : $font->getName() ?>
					<option style="font-family:<?php echo $font->getName() ?>;" value="<?php echo $displayText ?>"><?php echo $displayText ?></option>
				<?php endforeach; ?>
			</select>
			<!--h3 class="fake-select"><i class="fa fa-sort"></i></h3-->
		</div>	
	</div>
	<div class="pdc-item-tool pdc-fonts-sizes pdc_edit_text_only text-left" >	
		<span class="title">Size</span>
		<div class="">
			<div class="pdc-fonts-size pdc-fonts-size-2">
			<select class="pdc-style">
				<option>12</option>
				<option>14</option>
				<option>16</option>
				<option>18</option>
				<option>21</option>
				<option>25</option>
				<option>28</option>
				<option>32</option>
				<option>36</option>
				<option>42</option>
				<option>48</option>
				<option>56</option>
				<option>64</option>
				<option>72</option>
				<option>80</option>
				<option>88</option>
				<option>96</option>
				<option>104</option>
				<option>120</option>
				<option>144</option>
			</select>
			</div>
		</div>
	</div>
	<div class="pdc-item-tool2 pdc-more-tool">
		<!--a class="oj-show">							
			<i class="fa fa-caret-down"></i>
		</a-->
		<div class="pdc-list-tool">
			<div class="pdc-list-font pdc-list-item">
				<ul>
					<!--li class="text-right text-align pdc_edit_text_only">
						<div class="pdc-fonts-size pdc-fonts-size-2">
							
						</div>
					</li-->
					<li class="text-bold pdc_edit_text_only"><a><i class="plus-bold2"></i></a></li>
					<li class="text-italic pdc_edit_text_only"><a><i class="plus-italic2"></i></a></li>
					<li class="text-underline pdc_edit_text_only"><a><i class="plus-underline2"></i></a></li>
					<li class="text-left text-align on pdc_edit_text_only"><a><i class="plus-paragraph-left"></i></a></li>
					<li class="text-center text-align pdc_edit_text_only"><a><i class="plus-paragraph-center"></i></a></li>
					<li class="text-right text-align pdc_edit_text_only"><a><i class="plus-paragraph-right"></i></a></li>
					
				</ul>
			</div>
			<!--div class="pdc-list-align pdc-list-item">
				<span class="title"><?php echo __("Text Align") ?></span>
				<ul>
					<li class="text-left text-align on pdc_edit_text_only"><a><i class="plus-paragraph-left"></i></a></li>
					<li class="text-center text-align pdc_edit_text_only"><a><i class="plus-paragraph-center"></i></a></li>
					<li class="text-right text-align pdc_edit_text_only"><a><i class="plus-paragraph-right"></i></a></li>					
				</ul>
			</div-->			
		</div>
        
	</div>
	<div class="pdc-extra-align">
		<div class="pdc-extra-item">
			<label><?php echo __('Spacing') ?></label>
			<div class="pdc-sp-number pdc-sp-number-spacing">
				<div class="sp-minus"></div>
				<div class="sp-input">
					<input type="text" class="pdc-sp-input" id="pdc-spacing-input" value="0.0">
				</div>
				<div class="sp-plus"></div>
			</div>
		</div>
		<div class="pdc-extra-item">
			<label><?php echo __('Line height') ?></label>
			<div class="pdc-sp-number pdc-sp-number-line-height">
				<div class="sp-minus"></div>
				<div class="sp-input">
					<input type="text" class="pdc-sp-input" id="pdc-line-height-input" value="0.8">
				</div>
				<div class="sp-plus"></div>
			</div>
		</div>
		<div class="pdc-extra-item">
			<label><?php echo __("Color ") ?></label>
			<div class="pdc-item-tool pdc-colors text-right">
				<a  style="background: #000;" class="oj-show"><!--img src="<?php echo $block->getViewFileUrl('Magebay_Pdc::pdc/x3/images/color_picker.png') ?>" alt="" height="20px" /--></a>
				<ul class="pdc-color-list">
					<span class="pdc-color-list-close"><i class="fa fa-times-circle-o" aria-hidden="true"></i></span>
					<?php $i = 0; foreach($colors as $color)  :?>
					<?php 
					if(is_array($includeColors)) {
						if(!in_array($color->getColorId(), $includeColors)) continue;  
					} 
					?>
					<li><a style="background-color:#<?php echo $color->getColor_code(); ?>; color:#<?php echo $color->getColor_code(); ?>" title="<?php echo $color->getColor_name(); ?>"><!--span class="pdc-brightness-1"></span--></a></li>
				<?php $i++; endforeach;  ?>
					<?php if(isset($productConfig['note']['enable_colorpicker_plugin']) && $productConfig['note']['enable_colorpicker_plugin'] == "1") : ?>
					<li>
						<div pdc-data="color" id="pdc_color_picker">
							<div class="result">+</div>
						</div>
					</li>
					<?php endif; ?>
				</ul>
			</div>
		</div>
	</div>

	<div class="pdc-extra-font">
		<div class="pdc-extra-item">
			<label><?php echo __('Outline Size') ?></label>
			<div class="pdc-sp-number pdc-sp-number-outline">
				<div class="sp-minus"></div>
				<div class="sp-input">
					<input type="text" class="pdc-sp-input" id="pdc-outline-input" value="0.0">
				</div>
				<div class="sp-plus"></div>
			</div>
		</div>
		
		<div class="pdc-item-tool pdc-extra-item pdc-extra-color">
		<label><?php echo __("Color ") ?></label>
			<a class="oj-show"  style="background:#641bd1;"></a>
			<ul class="pdc-color-stock-list" style="display: none;">
				<span class="pdc-color-stock-list-close"><i class="fa fa-times-circle-o" aria-hidden="true"></i></span>
				<?php $i = 0; foreach($colors as $color)  :?>
				<?php 
				if(is_array($includeColors)) {
					if(!in_array($color->getColorId(), $includeColors)) continue;  
				} 
				?>
				<li><a style="background-color:#<?php echo $color->getColor_code(); ?>; color:#<?php echo $color->getColor_code(); ?>" title="<?php echo $color->getColor_name(); ?>"><!--span class="pdc-brightness-1"></span--></a></li>
				<?php $i++; endforeach;  ?>
				<?php if(isset($productConfig['note']['enable_colorpicker_plugin']) && $productConfig['note']['enable_colorpicker_plugin'] == "1") : ?>
				<li>
					<div pdc-data="color" id="pdc_color_picker_out_line">
						<div class="result">+</div>
					</div>
				</li>
				<?php endif; ?>
			</ul>
		</div>
		
	</div>
	<!--div class="pdc-item-tool pdc-fonts-size pdc_edit_text_only">
		<select class="pdc-style">
			<option>12</option>
			<option>14</option>
			<option>16</option>
			<option>18</option>
			<option>21</option>
			<option>24</option>
			<option>28</option>
			<option>32</option>
			<option>36</option>
			<option>42</option>
			<option>48</option>
			<option>56</option>
			<option>64</option>
			<option>72</option>
			<option>80</option>
			<option>88</option>
			<option>96</option>
			<option>104</option>
			<option>120</option>
			<option>144</option>
		</select>
		<h3 class="fake-select"><i class="fa fa-sort"></i></h3>
	</div-->
</div>
<div class="pdc-edit-tool pdc-edit-tool-right"  id="pdc_toolbar_options">
	<div class="pdc-edit-close"><i class="fa fa-times-circle-o" aria-hidden="true"></i></div>
	
	<div class="pdc-item-tool pdc-del-tool" data-toggle="tooltip" data-placement="top" title="Delete Element">
		<a class="oj-show"><i class="fa fa-trash"></i></a>
	</div>
	<div class="pdc-item-tool pdc-more-tool pdc-edit-tool-img" data-toggle="tooltip" data-placement="top" title="Edit Element">
		<div class="pdc-element-style"><a class="oj-show"><i class="fa fa-pencil-square-o"></i></a></div>
	</div>
	<div class="pdc-item-tool pdc-more-tool" data-toggle="tooltip" data-placement="top" title="Forward Element">
        <div class="pdc-element-forward pdc-element-style"><a class="oj-show"><i class="fa fa-arrow-up"></i></a></div>
    </div>
	<div class="pdc-item-tool pdc-more-tool" data-toggle="tooltip" data-placement="top" title="Backward Element">
        <div class="pdc-element-backward pdc-element-style"><a class="oj-show"><i class="fa fa-arrow-down"></i></a></div>
    </div>

	<div class="pdc-item-tool pdc-flipx pdc_edit_img_only" data-toggle="tooltip" data-placement="top" title="Flip Vertical">
        <a class="oj-show"><i class="plus-object-flip-ver"></i></a>
    </div>
    <div class="pdc-item-tool pdc-flipy pdc_edit_img_only" data-toggle="tooltip" data-placement="top" title="Flip Horizontal">
        <a class="oj-show"><i class="plus-object-flip-hor"></i></a>
    </div>	
	<div class="pdc-item-tool pdc-more-tool" data-toggle="tooltip" data-placement="top" title="Copy Element">
        <div class="dividerAbove pdc-element-copy pdc-element-style"><a class="oj-show"><i class="plus-copy"></i></a></div>
    </div>	
</div>