<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="popup-subscribe" style="background: url('http://beyoung.in/pub/media/wysiwyg/pop-newsletter2.jpg') no-repeat right;">
	<div class="em-wrapper-newsletter">
		<div class="em-block-title">
			<h2 style="font-size:28px;letter-spacing: 2px;text-align:center;"><span><?php echo __('Beyoung Newsletter') ?></span></h2>
			<h3 style="text-align:center;"><img src="http://beyoung.in/pub/media/wysiwyg/mailnews.png" width="100"></h3>
		</div>
		<p><?php echo __('Sign up to our email newsletter to be the first to hear about great offers and more') ?></p>
		<div class="em-newsletter-style05">
			<div class="block block-subscribe">
				<form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="popup-newsletter-validate-detail">
					<div class="block-content">
						<div class="form-subscribe-content">
							<div class="input-box">
							   <input name="email" type="email" id="newsletter" style="outline:none;"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
							</div>
							<div class="actions">
								<button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                    <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
                </button>
							</div>
						</div>
					</div>
				</form>				 
			</div>
		</div>
	</div>	
</div>
