<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<section>
		<div class="cntbdban" style="background: url('https://beyoung.in/pub/media/wysiwyg/beyoung-contact.jpg'); background-position: center top;">
			<div class="container">
				<div class="row">
						<div class="col-md-12">
							<h2 class="brdcm"></h2>
					</div>
				</div>
		</div>
	</div>
</section> 
<div class="col-sm-8 get_in_touch_col">
<div class="pagepadcnt">
					<div class="get_in_touch_contents">
					<h1 class="contpage">Address &amp; Location</h1>
					<div class="mapmap">
					<iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d6102.929747271627!2d73.72170931986807!3d24.560752437200595!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1s1-C-12%2C+Gayatri+Nagar%2C+Sector+5+Udaipur%2C+India+313002!5e0!3m2!1sen!2sin!4v1524470586935" width="100%" height="400" frameborder="0" style="border:0" allowfullscreen></iframe>
				</div>
			</div>
</div>
				</div>
<div class="col-sm-8 affitem">
<div class="pagepadcnt">
<form class="form contact"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset margbt" style="margin-bottom:20px;">
        <legend class="legend contpage"><span><?php /* @escapeNotVerified */ echo __('Write to Us') ?></span></legend><br />
        <div class="field note no-label" style="width:100%;"><?php /* @escapeNotVerified */ echo __('We would love to here from you') ?></div>
		<div style="clear:both;"></div>
        <div class="field name required">
            <label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Name') ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field telephone">
            <label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
            <div class="control">
                <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
            </div>
        </div>
        <div class="field comment required afftcmt">
            <label class="label" for="comment"><span><?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?></span></label>
            <div class="control">
                <textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
            </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button style="padding: 10px 30px; letter-spacing: 1px;" type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>
</div>
</div>

<div class="col-sm-8 contact_col">
<div class="pagepadcnt">
				<div class="contact_contents">
					<h1 class="contpage">Contact Us</h1>
					<div>
						<p><i class="fa fa-phone-square" aria-hidden="true"></i>&nbsp;&nbsp;(+91) 869-663-3366</p>
						<p><i class="fa fa-envelope" aria-hidden="true"></i>&nbsp;&nbsp;info@beyoung.in</p>
					</div>
					
					
				</div>
				<div class="follow_us_contents" style="padding-top: 30px;">
					<h1 class="contpage">Timing</h1>
					<div style="color: #333 !important; font-size: 16px !important;">
						<p>Open hours: 8.00-18.00 Mon-Sat</p>
						<p>Sunday: Closed</p>
					</div>
				</div>

				<!-- Follow Us -->

				<div class="follow_us_contents" style="padding-top: 30px;">
					<h1 class="contpage">Follow Us</h1>
					<div class="socialcnt">
					<ul>
						<li><a href="https://www.facebook.com/Beyoung-Folks-1926524024344292/" style="background-color: #3a61c9"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						<li><a href="https://twitter.com/BeyoungFolks" style="background-color: #41a1f6"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
						<li><a href="https://in.pinterest.com/beyoungf/" style="background-color: #8f6247"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
						<li><a href="https://plus.google.com/u/0/115944147813954899038" style="background-color: #41a1f6"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
						<li><a href="https://www.instagram.com/beyoung.in/" style="background-color: #8f6247"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
					</ul>
					</div>
				</div>
</div>
			</div>
