<?php 
$request = $this->getRequest()->getParams();
$ajaxParams = "";
if (isset($request['json']) && $request['json'] != "") {
	$ajaxParams .= "json/" . $request['json'] . "/";
}
if (isset($request['redesign']) && $request['redesign'] != "") {
	$ajaxParams .= "redesign/" . $request['redesign'] . "/";
}
if (isset($request['share']) && $request['share'] != "") {
	$ajaxParams .= "share/" . $request['share'] . "/";
}
?>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
</head>
<body style="background-color: transparent;" class="small-popup">
<div class="iframe-container" style="display: none;">
	<button style="display: none;" id="get_design_content"><?php echo __("Get Design Page") ?></button>
	<span id="close_iframe" class="close pdc-close"></span>
	<div class="pdc-wrapper" id="pdcwrapper">
		<div class="pdc-container">
			<div class="pdc-center">
				<div class="pdc_design_panel">
				<?php echo __("[DON'T CHANGE THIS FILE]") ?>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	jQuery(function($) {
		var mainWindow = top.document;
		var baseUrl = $("#base_url", mainWindow).val(),
			_ifMarginTop = "10px", 
			productId = "<?php echo $request['product-id']?>";
		
		LoadDesign = {
			pendingTime : 0,
			baseUrl : null,
			init : function() {
				setTimeout(function() {
					LoadDesign.getDesignPage();
				}, LoadDesign.pendingTime);
			},
			getDesignPage : function() {
				var isProductConfig = $('#is-product-config',mainWindow).val();
				if(!productId || productId == 'undefined')
                {
                    productId = $('#current_product_id',mainWindow).val();
                }
                var designUrl = baseUrl + "pdc/view/designtool/product-id/" + productId + "/area/customize/" + "<?php echo $ajaxParams?>";
				if(isProductConfig == '1')
                {
                    var productId = $('#current_product_id',mainWindow).val();
                    var jsonFile =  $('input[name="extra_options"]',mainWindow).val();
                    designUrl = baseUrl + "pdc/view/designtool/product-id/" + productId + "/area/customize/json/"+jsonFile;
                }
				LoadDesign.sendRequest(designUrl, function(response) {
					if (response != "") {
						$(".pdc_design_panel").html(response);
						LoadDesign.resizeIframe();
					}
				});
			},
			sendRequest : function(url, callback) {
				$.ajax({
					type : "GET",
					url : url,
					beforeSend : function () {
						//console.log("Sending request...");
						$(".pdp_loading").show();
					},
					success : function(data) {
						callback(data);
						$(".pdp_loading").hide();
					}
				});
			},
			resizeIframe : function() {
				$("#pdc_iframe", mainWindow).css({
					"width": "100%",
					"height" : "100%",
					"left" : "0",
					"top" : "0",
					"right" : "0"
				});
                $('.main-container', mainWindow).hide();
				LoadDesign.readyToDesign();
			},
			closeIframe : function() {
				$(document).on("click", '[pdc-action="close-iframe"]', function() {
					$("#pdc_iframe", mainWindow).css({"top" : "-100000px"}); console.log(232);
                    $('.main-container', mainWindow).show();
					$(".catalog-product-view", mainWindow).css({"overflow" : "inherit"});
				});
			}(),
			readyToDesign : function() {
				$(".loader").hide();
				$(".iframe-container").show();
				top.document.body.scrollTop = top.document.documentElement.scrollTop = 0;
			},
            //Custom theme might has different selector to main image box of product
			showSampleImage : function(mainImgBox) {
				var moveM1 = false;
				if($("#sample_images", mainWindow).length) {
					var sampleImageStr = $("#sample_images", mainWindow).val();
					if (sampleImageStr) {
						var optonValues = $('#extra_options_value',mainWindow).val();
						optonValues = JSON.parse(optonValues);
						var oldPath = '';
						if(optonValues)
						{
							for(var key in optonValues)
							{
								if(!isNaN(key))
								{
									if(optonValues[key] != 'undefined')
									{
										var backgroundPath = optonValues[key].background_path;
										if(backgroundPath && backgroundPath != 'undefined' && backgroundPath != '')
										{
											if(backgroundPath.indexOf('pub/media') !== -1)
											{
												var aroptonValues = backgroundPath.split('pub/media');
												oldPath = aroptonValues[0];
											}
											else if(backgroundPath.indexOf('media/pdp') !== -1)
											{
												moveM1 = true;
												var aroptonValues = backgroundPath.split('media');
												oldPath = aroptonValues[0];
											}
											
										}
									}
									
								}
							}
						}
						console.log(oldPath);
						var mBaseurl = $('#base_url',mainWindow).val();
						var sampleImageJson = JSON.parse(sampleImageStr);
                            // mainImgBox = mainImgBox || '.product .gallery-placeholder'; 
							var mainBoxDefault = '.product .gallery-placeholder'; 
							$(mainBoxDefault,mainWindow).after('<div class="pdc-product-image"></div>')
							$(mainBoxDefault,mainWindow).remove();
							mainImgBox = mainImgBox || '.product .pdc-product-image'; 
						if (sampleImageJson[0] && sampleImageJson[0].image_result) {
                            //Check if result image is svg format or png
                            var thumbnail = sampleImageJson[0].image_result,
                                thumbnailFormat = thumbnail.split(".").slice(-1)[0];
                            $(mainImgBox + ' img', mainWindow).hide();
                            $("#pdc-preview", mainWindow).remove();
							var tempSvg = sampleImageJson[0].image_result;
							if(oldPath != '' && mBaseurl != oldPath)
							{
								while(tempSvg.indexOf(oldPath) != -1)
								{
									if(moveM1)
									{
										tempSvg = tempSvg.replace(oldPath, mBaseurl+'pub/');
									}
									else
									{
										tempSvg = tempSvg.replace(oldPath, mBaseurl);
									}
								}
							}
							var svgPreviewObj = '<div id="pdc-preview" style="line-height: 0;">'+ tempSvg +'</div>';
							$(mainImgBox, mainWindow).html(svgPreviewObj);
						}
						//if ($('.more-views', mainWindow).length) {
                        $('.more-views', mainWindow).remove();
                        if($(mainImgBox + ' .pdp_more_view', mainWindow).length == 0){
                            $(mainImgBox, mainWindow).append('<div class="more-views" style="clear: both; float: left;"><h2><?php echo __('More Views');?></h2><ul class="pdp_more_view" style="line-height: 0;"></ul></div>');
                        }else{
                            $('.pdp_more_view', mainWindow).html('');
                        }
                        $.each(sampleImageJson, function(index, image) {
                            if(!image.image_result) return;
							var tempSvg2 = image.image_result;
							if(oldPath != '' && mBaseurl != oldPath)
							{
								while(tempSvg2.indexOf(oldPath) != -1)
								{
									if(moveM1)
									{
										tempSvg2 = tempSvg2.replace(oldPath, mBaseurl+'pub/');
									}
									else
									{
										tempSvg2 = tempSvg2.replace(oldPath, mBaseurl);
									}
									
								}
								
							}
							$('.pdp_more_view', mainWindow).append('<li style="margin: 0 5px; border: 1px solid #ccc; width: 70px; float: left; cursor: pointer; list-style: none;"><div class="pdc-more-view-item">'+ tempSvg2 +'</div></li>');
                        });
                        $('.pdp_more_view li .pdc-more-view-item', mainWindow).click(function(){
                            $("#pdc-preview", mainWindow).html($(this).html()); 
                        });
						$('#pdc-preview svg',mainWindow).css({"height": "100%","max-width" : "100%"});
						$('.pdc-more-view-item svg',mainWindow).css({"height": "100%","max-width" : "100%"});
						//}
					}
				}
				this.updateLinkwishlist();
			},
			reloadPrice : function() {
				/********************************** RELOAD PRICE **********************************/
				if(!$('#get_design_content').hasClass('loaded'))
				{
					return false;
				}
				var extraPrice = 0;
				if ($("#extra_options_value", mainWindow).length && $("#extra_options_value", mainWindow).val() != "") {
					var extraOptionsValue = JSON.parse($("#extra_options_value", mainWindow).val()),
						sampleCost = 0;
					if(extraOptionsValue !== undefined) {
						$.each(extraOptionsValue, function() {
							sampleCost += parseFloat(this.final_price);
						});
					}
					if (sampleCost) {
						extraPrice = parseFloat(sampleCost); 
					}
				}
				if ($(".product-custom-option", mainWindow).length) {
					$('#pdc-extract-price',mainWindow).val(extraPrice);
				}
				var reloadPriceUrl = baseUrl+ 'pdc/index/reloadPrice/product-id/'+productId+'/pdc-price/'+extraPrice;
				$.ajax({
					dataType : "json",
					type : "POST",
					url : reloadPriceUrl,
					data : $('#product_addtocart_form',mainWindow).serialize(),
					beforeSend : function () {

					},
					success : function(data) {
						if(data.status == 'success')
						{
							$('#product-price-'+productId+' span.price',mainWindow).html(data.finaPrice);
							if($('#old-price-'+productId,mainWindow).length)
							{
								$('#old-price-'+productId +' span.price',mainWindow).html(data.price);
							}
						}
					}
				});
				/********************************** End RELOAD PRICE **********************************/
			},
			updateLinkwishlist : function()
			{
				/* update data for add wishlist */
				console.log('Test aaaa');
				if($('a.towishlist',mainWindow).length)
				{
					var wlObj = $('a.towishlist',mainWindow).attr('data-post');
					wlObj = JSON.parse(wlObj);
					if(wlObj)
					{
						var wlData = wlObj.data;
						wlData.extra_options = $('input[name="extra_options"]',mainWindow).val();
						var wlAction = wlObj.action;
						wlAction = wlAction.replace("updateItemOptions","add");
						wlObj.data = wlData;
						wlObj.action = wlAction;
						$('a.towishlist',mainWindow).attr('data-post',JSON.stringify(wlObj));
					}
				}
				if($('a.tocompare',mainWindow).length)
				{
					var compareObj = $('a.tocompare',mainWindow).attr('data-post');
					compareObj = JSON.parse(compareObj);
					if(compareObj)
					{
						var compareData = compareObj.data;
						wlData.extra_options = $('input[name="extra_options"]',mainWindow).val();
						compareObj.data = compareData;
						var compareAction = compareObj.action;
						compareAction = compareAction.replace("updateItemOptions","add");
						compareObj.action = compareAction;
						$('a.tocompare',mainWindow).attr('data-post',JSON.stringify(wlObj));
					}
				}
			},
			getDesignPageClick : function() {
				$("#get_design_content").click(function() {
					top.document.body.scrollTop = top.document.documentElement.scrollTop = 0;
					$(".catalog-product-view", mainWindow).css({"overflow" : "hidden"});
					var isMainLoader = $('#is-pdc-popup-loader',mainWindow).val() || '0';
					if($(this).hasClass("loaded") && isMainLoader == '1') {
						//Show iframe
						$("#pdc_iframe", mainWindow).css({
							"top" : "0"
						});
                        $('.main-container', mainWindow).hide();
						return false;
					} else {
                        $(".pdc_design_panel").html('');
                        $("#pdc_iframe", mainWindow).css({
                            "width": "unset",
                            "height" : "unset",
                            "left" : "unset",
                            "top" : "unset",
                            "right" : "unset"
                        });
						var _initIframeW = 300;
						$("#pdc_iframe", mainWindow).css({
							"top" : ($(top.window).height() / 3) + "px",
							"left" : ($(top.window).width() - _initIframeW) / 2 + "px"
						});
					}
					$(this).addClass("loaded");
					$('#is-pdc-popup-loader',mainWindow).val(1);
					LoadDesign.init();
				});
			}(),
			autoClickCustomBtn : function() {
				if($("#pdp_design_action", mainWindow).length && $("#pdp_design_action", mainWindow).val() != "") {
					$("#get_design_content").click();
				}
			}
 		}
 		LoadDesign.autoClickCustomBtn();
        //Auto replace base image or note
        if($("input[name='extra_options']", mainWindow).length 
            && $("input[name='extra_options']", mainWindow).val() != "") {
            //Check config
            var pdcConfig = JSON.parse($("#pdc_product_config", mainWindow).val());
            var productConfig = pdcConfig.note;
			if(pdcConfig.note !== null && typeof pdcConfig.note == 'object')
			{
				
			}
			else
			{
				productConfig = JSON.parse(pdcConfig.note);
			}
            var isAutoReplace = productConfig.auto_replace_pattern || 2;
			isAutoReplace = parseInt(isAutoReplace);
            if($("#cart_item_id", mainWindow).val()) {
                isAutoReplace = 1;
            }
            //Edit action should replace base image
            if(isAutoReplace === 1) {
                LoadDesign.showSampleImage();
            }
        }
        LoadDesign.reloadPrice();
	});
</script>
</body>