<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<?php $settingHelper = $this->helper('Emthemes\ThemeSettings\Helper\Data'); ?>
<?php if($settingHelper->getConfig('general_section/general_blocks/handle_login_form') == 2): ?>
<div class="fade popup-login-wrapper" style="display:none">
    <div class="popup popup">
        <div class="popup-inner">           
            <div class="popup-content" data-role="content">
                  <div class="block block-customer-login popup-login" id="link-popup-login">   
                          <div class="block-content" aria-labelledby="block-customer-login-heading">
                          <form class="form form-login"
                                action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
                                method="post"
                                id="popup-login-form"
                                data-mage-init='{"validation":{}}'>
                              <?php echo $block->getBlockHtml('formkey'); ?>
                              <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">                
                                  <div class="field email required">
                                      <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                                      <div class="control">
                                          <input name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                                      </div>
                                  </div>
                                  <div class="field password required">
                                      <label for="pass" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
                                      <div class="control">
                                          <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true, 'validate-password':true}">
                                      </div>
                                  </div>
                                  <?php echo $block->getChildHtml('form_additional_info'); ?>
                                  <div class="actions-toolbar">
                                      <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('Login') ?></span></button></div>
                                      <div class="secondary"><a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span></a></div>
                                  </div>
                                <div class="pslogin-block pslogin-login">

                                <div class="pslogin-spacer pslogin-clearfix">
                                <span class="pslogin-title" style="display: none;">Login with your social account</span>
                                </div>

                                <!--<div class="pslogin-buttons pslogin-buttons-showfull">
                                <ul class="pslogin-clearfix">
                                <li class="pslogin-button facebook pslogin-visible" title="Login with Facebook">
                                <a class="pslogin-button-link pslogin-button-click" rel="nofollow" href="javascript:void(0);" data-href="http://dev.beyoung.in/pslogin/account/douse/type/facebook/refresh/1517912350/" data-width="650" data-height="350">

                                <img class="pslogin-button-image" src="https://beyoung.in/pub/media/pslogin/default/signin-facebook.png">


                                </a>
                                </li>
                                </ul>

                                </div>-->

                               <div class="social_button social_button_fb" onclick="processFB();"> <i class="fa fa-facebook" aria-hidden="true"></i> Register with Facebook</div>

                                <div class="social_button social_button_google" onclick="loginGoogle();"><i class="fa fa-google" aria-hidden="true"></i> Register with Google</div>

                                </div>
                              </fieldset>
                          </form>
                      </div>
                  </div>
            </div>

        </div>
    </div>
</div>

<script>
require([
        'jquery',
        'modal',
        'domReady!'
],function($){
      $('.log-in').click(function(){   
        	    $('#link-popup-login').modal({   
        	            autoOpen: true, 
                        wrapperClass: 'modals-wrapper popup-login',
                        responsive: true
                });
                return false;
  	});
});
</script>
<?php endif; ?>

