<input type="hidden" id="mst_base_url" value="<?php echo $block->getBaseUrl() ?>"/>
<div id="pdc-popup-modal-order" style="display : none;">
	<iframe id="pdc-iframe-order" style="width: 100%; height : 1000px;"></iframe>
</div>
<script>
    requirejs([
        'jquery',
		'Magento_Ui/js/modal/modal'
    ], function($,modal){
		 PDCOrderView = {
			reOrderAdditionalInfo : function() {
				var itemId, customizeLink;
				$(".view-customize-design").hide();
				if($(".edit-order-table td.col-product").length) {
					$(".edit-order-table td.col-product").each(function() {
						//console.info($(this));
						itemId = $(this).find('.product-title').closest("div").attr("id").split('_')[2];
						customizeLink = $("#customize-" + itemId).html();
						$(this).append(customizeLink);
					});
				} else {
					//Bundle product might be
					// if($(".view-customize-design")) {
					//     $(".view-customize-design").each(function() {
					//         var itemId = $(this).attr("id").replace("customize-", "");
					//         var row = $("#order_item_"+ itemId +"_title").closest("td");
					//         var customizeLink = $("#customize-" + itemId).html();
					//         row.append(customizeLink);
					//     });
					//}
				}
			}(),
			viewDesignItemInOrder : function() {
			   var baseUrl = $("#mst_base_url").val()
				$("#sales_order_view").on("click", '.pdp-order-item', function(e) {
					productId = $(this).attr('productid');
					itemId = $(this).attr('itemid');
					orderId = $(this).attr('orderid');
					url = baseUrl + "pdc/view/finaldesign/product-id/"+ productId + "/order-id/" + orderId + "/item-id/" + itemId;
					var options = {
							type: 'slide',
							responsive: true,
							//innerScroll: true,
							title: '<?php echo __('') ?>',
							buttons: []
						};
						var popup = modal(options, $('#pdc-popup-modal-order'));
						$('#pdc-popup-modal-order').modal('openModal');
						$("#pdc-iframe-order").attr('src', url);
						e.preventDefault();
				})
			}()
		 }
    });
</script>