<div class="image-action-btn">
	<button class="image-action-item" id="image-action-backwite" type="button"><span><?php echo __("Back/White") ?></span></button>
</div>
<div class="image-action-content">
	<div class="image-action-content-item" id="image-action-backwite-content" style="display : none;">
		<span class="image-brightness-content">
			<label><?php echo __('Brightness') ?></label> <span id="image-backwite-brightness-label">0%</span>
			<input value="0" min="-255" max="255" id="image-backwite-brightness" type="range">
		</span>
		<span class="image-contrast-content">
			<label><?php echo __('Contrast') ?></label> <span id="image-backwite-contrast-label">0%</span>
			<input value="0" min="-255" max="255" id="image-backwite-contrast" type="range">
		</span>
		<span class="image-gradient-transparency-content">
			<label><?php echo __('GradientTransparency') ?></label> <span id="image-gradient-transparency-label">40%</span>
			<input value="100" min="0" max="255" id="image-gradient-transparency" type="range">
		</span>
	</div>
</div>